module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'bug',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'test-p',
        'build',
        'ci',
        'chore',
        'revert',
        'workflow',
        'mod',
        'wip',
        'types',
        'merge',
        'editor',
      ],
    ],
    'subject-case': [
      2,
      'never',
      ['sentence-case', 'start-case', 'pascal-case', 'upper-case'],
    ],
    'subject-full-stop': [2, 'never', '.'],
    'header-max-length': [2, 'always', 72],
  },
};
